# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_report_get_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
