# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-22 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='passwd',
            field=models.CharField(max_length=400),
        ),
    ]
