# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-22 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190622_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=30)),
                ('sex', models.BooleanField(default=0)),
                ('email', models.EmailField(default='123@gmail.com', max_length=254)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('hobby', models.CharField(default='play ball', max_length=100)),
            ],
        ),
    ]
